[project]
name = "ai-warmup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Veera V Nageswara Rao Matukumalli", email = "v.matukumalli@gainwelltechnologies.com" }
]
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.80",
    "fastmcp>=4.0.2",
    "litellm>=1.98.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ai-warmup = "ai_warmup:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
